const INITIAL_STATE = {
    "First Name": "",
    "Middle Name": "",
    "Last Name": "",
    Age: 18,
    Gender: "",
    "Permanent Address": "",
    "Contact Number": "",
    "Email Address": "",
    College: "",
    Program: "",
    Major: "",
    Batch: "",
    "Highest Educational Attainment ": "",
    "SR-Code": "",
    "G-suite account": "",
    "Current Nature of Work/Profession Field": {
        "Architecture, Planning & Environmental Design": false,
        Education: false,
        International: false,
        "Arts & Entertainment": false,
        "Engineering & Computer Science": false,
        "Law & Public Policy": false,
        Business: false,
        Environment: false,
        "Science - Biological & Physical": false,
        Communications: false,
        Government: false,
        "Social Impact": false,
        "Health & Medicine": false,
        Other: false,
    },
    "Name of Job": "",
    "Employment Status": "",
    "Employment Characteristic": "",
    "Status of Professional Registration": "",
    "Location of Work": "",
    "Company Name": "",
    "Length of Time before Employment": {
        "Less than 1 month": false,
        "1-6 months": false,
        "7-11 months": false,
        "1 year to less than 2 years": false,
        "2 years to less than 3 years": false,
        "3 years to less than 4 years": false,
    },
    "Job Satisfaction": "",
    "Is your college degree relevant to your job?": "",
    "Overall, how would you rate the usefulness of your studies?": {
        "For finding an adequate job after finishing your studies": "",
        "For fulfilling your present professional tasks, if applicable": "",
        "For your future professional development/career": "",
        "For the development of your personality": "",
        "For the economic development of your country": "",
    },
    "Previous Nature of Work": {
        "Architecture, Planning & Environmental Design": false,
        Education: false,
        International: false,
        "Arts & Entertainment": false,
        "Engineering & Computer Science": false,
        "Law & Public Policy": false,
        Business: false,
        Environment: false,
        "Science - Biological & Physical": false,
        Communications: false,
        Government: false,
        "Social Impact": false,
        "Health & Medicine": false,
        Other: false,
    },
    "Reason/s of changing job": {
        "Low salary": false,
        "To explore new environment": false,
        "Health related concerns": false,
        "To experience new job": false,
        Other: false,
    },
    "Reason/s of unemployment": {
        "Further studies": false,
        "Family concerns": false,

        "Health related reasons": false,

        "No job opportunity": false,

        "Did not apply for a job yet": false,
        "Qualifications did not fit job": false,
        "Lack of work experience": false,
        Other: false,
    },
    "Is the curriculum you've finished relevant to your current job?": "",
    "What are the competencies you've learned in college in which you find useful in your current job?":
        {
            "Communication Skills": false,
            "Human relation skills": false,
            "Problem solving skills": false,
            "Information technology skills": false,
            "Entrepreneurial skills": false,
            "Critical thinking skills": false,
            "Teaching skills": false,
            "Laboratory/ technical skills": false,
            "Time management": false,
            "Analytical skills": false,
            "Surveying skills": false,
            "Leadership skills": false,
            "Entertainment skills": false,
            "Research skills": false,
            "Ethical skills": false,
            Other: false,
        },
};

const alumniTrackingReducer = (state, action) => {
    switch (action.type) {
        case "field":
            return { ...state, [action.field]: action.value };
        default:
            return state;
    }
};
